services:
  ajsystem_admin.funcionario:
    class: AjSystem\AdminBundle\Services\Funcionario
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@security.token_storage"

  ajsystem_admin.servico:
    class: AjSystem\AdminBundle\Services\Servico
    arguments:
      - "@doctrine.orm.entity_manager"
      - "@security.token_storage"

  ajsystem_admin.cliente:
    class: AjSystem\AdminBundle\Services\Cliente
    arguments:
    - "@doctrine.orm.entity_manager"
    - "@security.token_storage"